name: Update contributors

on:
  pull_request:
    types: [submitted]
  pull_request_review:
    tyoes: [submitted]
  push:
    branches:
        - master 
jobs:
  update-levels:

    runs-on: ubuntu-latest
    env:
      DEV_PROD: ${{ secrets.GCP_BD_DEV_PROD }}
      DEV_STAG: ${{ secrets.GCP_BD_DEV_STAGING }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Update Contributors
      uses: ./.github/workflows/update-contributors